# permissions for end users to view simpleapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simpleapp-viewer-role
rules:
- apiGroups:
  - webapp.k8s.cmm.io
  resources:
  - simpleapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.k8s.cmm.io
  resources:
  - simpleapps/status
  verbs:
  - get
