name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      dockertag: ${{ steps.dockertag.outputs.dockertag }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set docker tag to build
        id: dockertag
        run: echo "::set-output name=dockertag::ghcr.io/${{ github.repository }}:${{ github.sha }}"

      - name: Build Docker Container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.dockertag.outputs.dockertag }}
